### ISSUE TITLE
[Crash] Calling from Java

### ISSUE THREAD

**Issue by mmacagno** [G00fY2/quickie#17]
Hello and thanks for this library, saved me a ton of work.

I am trying to provide a custom builder to the launcher but I get an internal exception.
Not sure if I am doing something wrong or else.

Here is the relevant code (Java):

`
private final ActivityResultLauncher barCodeScannerLauncher = this.registerForActivityResult(new ScanQRCode(), (ActivityResultCallback<QRResult>) result -> onQrCodeScannerResponse(result));;
`
...
`
          ScannerConfig.Builder configBuilder = new ScannerConfig.Builder();

//            It works with null, it crashed with custom builder
//            barCodeScannerLauncher.launch(null);
            barCodeScannerLauncher.launch(configBuilder
                    .setBarcodeFormats(Arrays.asList(BarcodeFormat.FORMAT_QR_CODE))
                    .setOverlayStringRes(R.string.activity_main_press_back)
                    .setHapticSuccessFeedback(true)
                    .setShowTorchToggle(false)
                    .build());
` 

And this is the crash:

`
    --------- beginning of crash
2021-08-06 12:41:40.631 7758-7758/io.sensoria.motus.watch E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.sensoria.motus.watch, PID: 7758
    java.lang.RuntimeException: Unable to resume activity {io.sensoria.motus.watch/io.sensoria.motus.activities.QrCodeScannerActivity}: java.lang.ClassCastException: io.github.g00fy2.quickie.config.ScannerConfig cannot be cast to java.lang.Void
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3845)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3877)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6865)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: io.github.g00fy2.quickie.config.ScannerConfig cannot be cast to java.lang.Void
        at io.github.g00fy2.quickie.ScanQRCode.createIntent(ScanQRCode.kt:17)
        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:168)
        at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:162)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
        at io.sensoria.motus.activities.QrCodeScannerActivity.lambda$onMandatoryPermissionsGranted$5$QrCodeScannerActivity(QrCodeScannerActivity.java:261)
        at io.sensoria.motus.activities.-$$Lambda$QrCodeScannerActivity$RmJSyqq0dqwqYcz7r9d_u2pyywY.run(Unknown Source:2)
        at android.app.Activity.runOnUiThread(Activity.java:7752)
...
other part of the stack not relevant
`

I am calling from UI thread.

**Comment by mmacagno** [comment]
I found the issue, I need to use ScanCustomCode() in the ActivityResultLauncher...
Closing.
