### ISSUE TITLE
Failed to open the camera in mode: "Do Not Disturb"

### ISSUE THREAD

**Issue by jeluchu** [G00fY2/quickie#57]
I don't know if there will be any clear solution for this kind of errors, but in some devices with API Level 28 the camera cannot be accessed when the device is in "Do Not Disturb" mode, in this case according to Firebase, the device model for help is R15 Pro of OPPO brand

```
Caused by java.util.concurrent.ExecutionException: sx2: p60: w40: Some API 28 devices cannot access the camera when the device is in "Do Not Disturb" mode. The camera will not be accessible until "Do Not Disturb" mode is disabled.
       at androidx.concurrent.futures.AbstractResolvableFuture.getDoneValue(AbstractResolvableFuture.java:518)
       at androidx.concurrent.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:475)
       at androidx.concurrent.futures.CallbackToFutureAdapter$SafeFuture.get(CallbackToFutureAdapter.java:199)
       at androidx.camera.core.impl.utils.futures.FutureChain.get(FutureChain.java:155)
       at androidx.camera.core.impl.utils.futures.ChainingListenableFuture.get(ChainingListenableFuture.java:105)
       at io.github.g00fy2.quickie.QRScannerActivity.startCamera$lambda-5(QRScannerActivity.java:88)
       at com.google.android.exoplayer2.video.VideoRendererEventListener$EventDispatcher$$InternalSyntheticLambda$1$1fd5b85d7b8d7fe3fd17f83c26e057a0b1efab8c89366a128fb356de74f064f9$0.run$bridge(VideoRendererEventListener.java:43)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:232)
       at android.app.ActivityThread.main(ActivityThread.java:7240)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```

**Comment by G00fY2** [comment]
Hi @jeluchu, thanks for reaching out! This error is new to me. But it seems to be an platform level error on early API 28 devices:  https://issuetracker.google.com/issues/149413835#comment10

There I nothing really I can do on my side. Since this can occur only on very few devices (not all API 28). Looks like there is no workaround for this. :pensive: If you see a lot of errors and really depend on the camera feature, I would suggest you check the exception returned by quickie and show an error dialog about the camera not being available when "Do Not Disturb" is turned on.
